let restaurants =[
    {
        name:"heaven",
        image:"",
        address:"",
        location:"",
        menu:[
            {
                item:"pizza",
                price:"2000rwf"
            },
            {
                item:"pizza",
                price:"2000rwf"
            },
            {
                item:"pizza",
                price:"2000rwf"
            }
        ]
    },
    {
        name:"java",
        image:"",
        address:"",
        location:"",
        menu:[
            {
                item:"pizza",
                price:"2000rwf"
            },
            {
                item:"pizza",
                price:"2000rwf"
            },
            {
                item:"pizza",
                price:"2000rwf"
            }
        ]
    }
]