let hotels =[
    {
        name:"heaven",
        image:"https://res.cloudinary.com/drof5meln/image/upload/v1681932371/enjoyk/hvn2_dlvbkj.jpg",
        address:"kiyovu",
        location:"7 KN 29 St, Kigali",
        menu:[
            {
                item:"pizza",
                price:"8000rwf"
            },
            {
                item:"burger",
                price:"5000rwf"
            },
            {
                item:"chicken fries",
                price:"7000rwf"
            }
        ]
    },
    {
        name:"pilipili",
        image:"https://res.cloudinary.com/drof5meln/image/upload/v1682081824/poivrenoir/pilipili/Pili-Pili-Bistro-Lounge-Bar-Pool-Kigali-36_nwll41.jpg",
        address:"kibagabaga",
        location:"12 KG 303 St,",
        menu:[
            {
                item:"pizza",
                price:"4000rwf"
            },
            {
                item:"pizza",
                price:"2000rwf"
            },
            {
                item:"pizza",
                price:"2000rwf"
            }
        ]
    },
    {
        name:"poivre-noir",
        image:"https://res.cloudinary.com/drof5meln/image/upload/v1682081103/poivrenoir/poivre-noir-kigali_zetqsx.jpg",
        address:" KG 670 St, Kigali",
        location:"kimihurura",
        menu:[
            {
                item:"pizza",
                price:"4000rwf"
            },
            {
                item:"pizza",
                price:"2000rwf"
            },
            {
                item:"pizza",
                price:"2000rwf"
            }
        ]
    },
      {
        name:"poivre-noir",
        image:"https://res.cloudinary.com/drof5meln/image/upload/v1682081103/poivrenoir/poivre-noir-kigali_zetqsx.jpg",
        address:" KG 670 St, Kigali",
        location:"kimihurura",
        menu:[
            {
                item:"pizza",
                price:"4000rwf"
            },
            {
                item:"pizza",
                price:"2000rwf"
            },
            {
                item:"pizza",
                price:"2000rwf"
            }
        ]
    }, 
     {
        name:"poivre-noir",
        image:"https://res.cloudinary.com/drof5meln/image/upload/v1682081103/poivrenoir/poivre-noir-kigali_zetqsx.jpg",
        address:" KG 670 St, Kigali",
        location:"kimihurura",
        menu:[
            {
                item:"pizza",
                price:"4000rwf"
            },
            {
                item:"pizza",
                price:"2000rwf"
            },
            {
                item:"pizza",
                price:"2000rwf"
            }
        ]
    }
  
]
